/**
 * typert.host.ts — Hand-written Typert host protocol definition.
 *
 * Modeled on dsh-api-workspace-files/lib/typert.host.js.
 * In a full DSH build this would be generated by @deepseek-ai/dsh-typert-generator
 * from the FaceModel. Hand-written here for standalone bundling.
 */

import { z } from "zod";

// ---------------------------------------------------------------------------
// Parameter schemas
// ---------------------------------------------------------------------------

const ShowParams = z.object({
  root: z.string(),
  revision: z.string().optional(),
  mode: z.enum(["types", "signatures"]),
  paths: z.array(z.string()).optional(),
  areas: z.array(z.string()).optional(),
});

const DiffParams = z.object({
  root: z.string(),
  base: z.string(),
  target: z.string(),
  mode: z.enum(["types", "signatures"]),
  paths: z.array(z.string()).optional(),
  areas: z.array(z.string()).optional(),
});

// ---------------------------------------------------------------------------
// Result schemas
// ---------------------------------------------------------------------------

const ShowResult = z.object({
  schema: z.literal("codect.show.v1"),
  input: z.enum(["revision", "stdin", "worktree"]),
  revision: z.string(),
  mode: z.enum(["types", "signatures"]),
  files: z.array(z.object({
    path: z.string(),
    language: z.string(),
    projection: z.object({
      text: z.string(),
      items: z.array(z.object({
        stable_key: z.string(),
        parent_key: z.string().nullable(),
        kind: z.string(),
        name: z.string(),
        span: z.object({
          start_line: z.number(),
          end_line: z.number(),
          start_byte: z.number(),
          end_byte: z.number(),
        }),
        canonical_text: z.string(),
      })),
    }),
    outline: z.array(z.object({
      stable_key: z.string(),
      parent_key: z.string().nullable(),
      kind: z.string(),
      name: z.string(),
      span: z.object({
        start_line: z.number(),
        end_line: z.number(),
        start_byte: z.number(),
        end_byte: z.number(),
      }),
      signature: z.string(),
    })),
  })),
});

const DiffRevision = z.object({
  kind: z.enum(["commit", "worktree", "index", "empty"]),
  revision: z.string(),
  id: z.string(),
});

const DiffSide = z.object({
  snapshot_id: z.string(),
  projection: z.object({
    text: z.string(),
    items: z.array(z.any()),
  }),
  outline: z.array(z.any()),
});

const DiffResult = z.object({
  schema: z.literal("codect.diff.v1"),
  mode: z.enum(["types", "signatures"]),
  base: DiffRevision,
  target: DiffRevision,
  files: z.array(
    z.object({
      path: z.string(),
      language: z.string(),
      status: z.enum(["added", "deleted", "modified"]),
      base: DiffSide.nullable(),
      target: DiffSide.nullable(),
      equal: z.literal(false),
    })
  ),
});

// ---------------------------------------------------------------------------
// TYPERT export
// ---------------------------------------------------------------------------

export const TYPERT = {
  package: "@nixypanda/dsh-codect",
  face: "host",
  schemas: [],
  invocations: [
    {
      id: "@nixypanda/dsh-codect#codect/show",
      service: "codect",
      namespace: "codect",
      method: "show",
      invocation: { kind: "direct" },
      parameters: [
        {
          name: "params",
          wire: "params",
          source: "json",
          codec: {
            mode: "strict",
            typeSymbol: "@nixypanda/dsh-codect/types#ShowParams",
            create: () => ShowParams,
          },
        },
      ],
      result: {
        mode: "strict",
        typeSymbol: "@nixypanda/dsh-codect/types#ShowResult",
        create: () => ShowResult,
      },
    },
    {
      id: "@nixypanda/dsh-codect#codect/diff",
      service: "codect",
      namespace: "codect",
      method: "diff",
      invocation: { kind: "direct" },
      parameters: [
        {
          name: "params",
          wire: "params",
          source: "json",
          codec: {
            mode: "strict",
            typeSymbol: "@nixypanda/dsh-codect/types#DiffParams",
            create: () => DiffParams,
          },
        },
      ],
      result: {
        mode: "strict",
        typeSymbol: "@nixypanda/dsh-codect/types#DiffResult",
        create: () => DiffResult,
      },
    },
  ],
  model: {
    services: [
      {
        description: "Codect focused projection and diff service.",
        summary: "Codect focused projection and diff service.",
        tags: [],
        key: "codect",
        exportName: "CodectService",
        members: [
          {
            kind: "method",
            name: "show",
            signature:
              "@Remote async show(params: ShowParams): Promise<ShowResult>",
            summary: "Run codect show --format json and return the projection document.",
          },
          {
            kind: "method",
            name: "diff",
            signature:
              "@Remote async diff(params: DiffParams): Promise<DiffResult>",
            summary: "Run codect diff --format json and return the focused diff document.",
          },
        ],
        types: [
          {
            name: "ShowParams",
            declaration: `export interface ShowParams {
              root: string;
              revision?: string;
              mode: "types" | "signatures";
              paths?: string[];
              areas?: string[];
            }`,
          },
          {
            name: "DiffParams",
            declaration: `export interface DiffParams {
              root: string;
              base: string;
              target: string;
              mode: "types" | "signatures";
              paths?: string[];
              areas?: string[];
            }`,
          },
        ],
      },
    ],
    events: [],
    objects: [],
  },
} as const;
