/**
 * typert.remote-client.ts — Hand-written Client FaceModel contribution.
 *
 * Modeled on dsh-api-workspace-files/lib/typert.remote-client.js: the module
 * exports a `TYPERT_REMOTE` contribution ({ package, descriptors }) that the
 * plugin's client half mounts with `ctx.remote.$mount(TYPERT_REMOTE)`. Mounting
 * installs the `remote.codect` namespace the sidebar views call.
 *
 * The Client gateway only reads `codec.mode` / `codec.typeSymbol` and (when
 * present) `codec.decode`; it never materializes the schemas, so the codecs
 * here stay dependency-free instead of importing zod into the browser bundle.
 *
 * In a full DSH build this would be generated by
 * @deepseek-ai/dsh-typert-generator from the Host FaceModel.
 */

/**
 * A strict JSON codec placeholder. The Client never calls `create`; a
 * pass-through schema keeps a future materialization harmless.
 */
function jsonCodec(typeSymbol: string) {
  return {
    mode: "strict" as const,
    typeSymbol,
    create: () => ({
      parse: (value: unknown) => value,
      safeParse: (value: unknown) => ({ success: true as const, data: value }),
    }),
  };
}

// ---------------------------------------------------------------------------
// Remote contribution
// ---------------------------------------------------------------------------

export const TYPERT_REMOTE = {
  package: "@nixypanda/dsh-codect",
  descriptors: [
    {
      id: "@nixypanda/dsh-codect#codect/show",
      service: "codect",
      namespace: "codect",
      method: "show",
      invocation: { kind: "direct" },
      parameters: [
        {
          name: "params",
          wire: "params",
          source: "json",
          codec: jsonCodec("@nixypanda/dsh-codect/types#ShowParams"),
        },
      ],
      result: jsonCodec("@nixypanda/dsh-codect/types#ShowResult"),
    },
    {
      id: "@nixypanda/dsh-codect#codect/diff",
      service: "codect",
      namespace: "codect",
      method: "diff",
      invocation: { kind: "direct" },
      parameters: [
        {
          name: "params",
          wire: "params",
          source: "json",
          codec: jsonCodec("@nixypanda/dsh-codect/types#DiffParams"),
        },
      ],
      result: jsonCodec("@nixypanda/dsh-codect/types#DiffResult"),
    },
  ],
} as const;

export default TYPERT_REMOTE;
