[package]
name = "ownai-language-elm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
ownai-core.workspace = true
tree-sitter.workspace = true
tree-sitter-elm.workspace = true
thiserror.workspace = true
unicode-width.workspace = true
